apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-tools
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/bondarieva-25b/platform-tools
  ref:
    branch: main
