apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kube-state-metrics
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kube-state-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: {{ .Release.Name }}-kube-state-metrics
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
          ports:
            - name: metrics
              containerPort: 8080
            - name: telemetry
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: telemetry
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.kubeStateMetrics.resources.requests.cpu }}
              memory: {{ .Values.kubeStateMetrics.resources.requests.memory }}
            limits:
              memory: {{ .Values.kubeStateMetrics.resources.limits.memory }}
