apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-server-headless
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      serviceAccountName: {{ .Release.Name }}-server
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.server.retention }}"
            - "--web.enable-lifecycle"
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              memory: {{ .Values.server.resources.limits.memory }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-server-config
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.server.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.server.storage.size }}
