apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-admin-creds
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.grafana.secretsManagerSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "admin-user"
          - path: "password"
            objectAlias: "admin-password"
  secretObjects:
    - secretName: {{ .Release.Name }}-credentials
      type: Opaque
      data:
        - objectName: admin-user
          key: admin-user
        - objectName: admin-password
          key: admin-password
