serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN_PLACEHOLDER

replicas: 1

controller:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

settings:
  clusterName: fp-eks
  clusterEndpoint: CLUSTER_ENDPOINT_PLACEHOLDER
  interruptionQueue: fp-eks-karpenter
