serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN_PLACEHOLDER

settings:
  clusterName: fp-eks
  clusterEndpoint: CLUSTER_ENDPOINT_PLACEHOLDER
  interruptionQueue: fp-eks-karpenter
