global:
  imagePullSecrets: []
  _placeholder: true

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride:
fullnameOverride:

commonLabels: {}

serviceAccount:
  create: true
  labels: {}
  # === DEV OVERRIDE ===
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058316962389:role/fp-eks-external-dns-role
  name:
  automountServiceAccountToken: true

service:
  annotations: {}
  port: 7979
  ipFamilies: []
  ipFamilyPolicy:

rbac:
  create: true
  additionalPermissions: []

deploymentAnnotations: {}

extraContainers: []

deploymentStrategy:
  type: Recreate

revisionHistoryLimit:

podLabels: {}
podAnnotations: {}

automountServiceAccountToken: true
shareProcessNamespace: false

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

priorityClassName:
terminationGracePeriodSeconds:

dnsPolicy:
dnsConfig:

initContainers: []

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop: ["ALL"]

env: []

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

extraVolumes: []
extraVolumeMounts: []

resources: {}

nodeSelector: {}
affinity: {}
topologySpreadConstraints: []
tolerations: []

serviceMonitor:
  enabled: false
  additionalLabels: {}
  annotations: {}
  namespace:
  interval:
  scrapeTimeout:
  scheme:
  tlsConfig: {}
  bearerTokenFile:
  relabelings: []
  metricRelabelings: []
  targetLabels: []

# === DEV OVERRIDES ===
logLevel: debug
logFormat: text

interval: 1m
triggerLoopOnEvent: false

namespaced: false
gatewayNamespace:

# === DEV OVERRIDE ===
sources:
  - ingress

# === DEV OVERRIDE ===
policy: sync

registry: txt
# === DEV OVERRIDE ===
txtOwnerId: fp-eks
txtPrefix:
txtSuffix:

# === DEV OVERRIDE ===
domainFilters:
  - team312.com

excludeDomains: []

labelFilter:
# === DEV OVERRIDE ===
annotationFilter: "external-dns.alpha.kubernetes.io/hostname"
annotationPrefix:

managedRecordTypes: []

provider:
  # === DEV OVERRIDE ===
  name: aws
  webhook:
    image:
      repository:
      tag:
      pullPolicy: IfNotPresent
    env: []
    args: []
    extraVolumeMounts: []
    resources: {}
    securityContext: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 2
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    service:
      port: 8080
    serviceMonitor:
      interval:
      scheme:
      tlsConfig: {}
      bearerTokenFile:
      scrapeTimeout:
      metricRelabelings: []
      relabelings: []

extraArgs: {}

secretConfiguration:
  enabled: false
  mountPath:
  subPath:
  data: {}
